# Generated by Django 4.1 on 2022-10-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('CAR', 'CAR'), ('BIKE', 'BIKE')], max_length=100),
        ),
    ]
