# Generated by Django 4.1 on 2022-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='max_bike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='max_car',
            field=models.IntegerField(default=0),
        ),
    ]
