# Generated by Django 4.1.1 on 2022-09-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=5)),
                ('phone_no', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('car_manufacturer', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_plates', models.CharField(max_length=10)),
                ('car_color', models.CharField(max_length=10)),
                ('parking_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(choices=[('B', 'BIKE'), ('C', 'CAR'), ('S', 'SUV')], max_length=1)),
                ('parking_booked', models.CharField(default='?', max_length=3)),
                ('late_in', models.BooleanField(default=False)),
                ('late_out', models.BooleanField(default=False)),
            ],
        ),
    ]
