# Generated by Django 4.1 on 2022-11-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_customer_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='available',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='preBooking',
        ),
    ]
