# Generated by Django 4.1 on 2022-10-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_parking_max_bike_parking_max_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='reserved',
        ),
        migrations.AddField(
            model_name='parking',
            name='bike_spots_reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='car_spots_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
