# Generated by Django 4.1 on 2022-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_parking_reserved_parking_bike_spots_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='preBooking',
            field=models.IntegerField(default=0),
        ),
    ]
