# Generated by Django 4.1 on 2022-11-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_parking_available_remove_parking_prebooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Reservation',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'STAFF'), (3, 'Reservation')], default=1, max_length=10),
        ),
    ]
