# Generated by Django 4.1 on 2022-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_parking_prebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='check_out',
            field=models.DateField(),
        ),
    ]
