# Generated by Django 4.1.1 on 2022-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'STAFF'), (3, 'CUSTOMER')], default=1, max_length=10),
        ),
    ]
