# Generated by Django 4.1 on 2022-11-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_customer_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.parking')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.reservation')),
            ],
        ),
    ]
