# Generated by Django 4.1 on 2022-10-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_customer_check_in_alter_customer_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
