# Generated by Django 4.1.1 on 2022-09-20 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='late_in',
            field=models.CharField(default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='late_out',
            field=models.BooleanField(default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
