# Generated by Django 4.1 on 2022-11-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_parking_option_connection_parking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='car_parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='portal.parking'),
        ),
    ]
