# Generated by Django 4.1 on 2022-10-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_customer_check_in_alter_customer_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='car_parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.parking'),
        ),
    ]
