# Generated by Django 4.1.1 on 2022-09-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_customer_late_in_alter_customer_late_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='late_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='late_out',
        ),
    ]
