# Generated by Django 4.1 on 2022-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_customer_car_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prebooking_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='parking_booking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
