# Generated by Django 4.1 on 2022-11-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_reservation_car_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='bike_spots_reserved',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='car_spots_reserved',
        ),
    ]
