# Generated by Django 4.1 on 2022-10-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_customer_prebooking_marked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prebooking_marked',
        ),
    ]
