# Generated by Django 4.1.1 on 2022-09-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='car_manufacturer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='car_plates',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='parking_booked',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='parking_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_type',
        ),
    ]
