# Generated by Django 4.1.1 on 2022-09-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_customer_car_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='room',
        ),
    ]
