# Generated by Django 4.1.1 on 2022-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_customer_check_in_customer_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='car_manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='car_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='car_parking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='car_plates',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='parking_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('C', 'CAR'), ('B', 'BIKE'), ('S', 'SUV')], max_length=100),
        ),
    ]
