# Generated by Django 4.1.1 on 2022-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_customer_car_color_customer_car_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(1, 'CAR'), (2, 'BIKE'), (3, 'SUV')], max_length=100),
        ),
    ]
