# Generated by Django 4.1.1 on 2022-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_customer_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='parking_booking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
