# Generated by Django 4.1 on 2022-10-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_customer_parking_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.IntegerField(blank=True)),
                ('reserved', models.IntegerField(blank=True)),
                ('available', models.IntegerField(blank=True)),
            ],
        ),
    ]
