# Generated by Django 4.1 on 2022-10-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='available',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='reserved',
        ),
    ]
