# Generated by Django 4.1 on 2022-10-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_remove_parking_available_remove_parking_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
