# Generated by Django 4.1 on 2022-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_parking_available_parking_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
